version: '3.8'

services:
  mysql:
    image: registry.dockermirror.com/library/mysql:8.0.37-oraclelinux9
    container_name: zabbix-mysql
    environment:
      MYSQL_DATABASE: zabbix
      MYSQL_USER: zabbix
      MYSQL_PASSWORD: huoxingxiaoliu
      MYSQL_ROOT_PASSWORD: huoxingxiaoliu
    volumes:
      - /var/lib/mysql:/var/lib/mysql
    networks:
      - zabbix-net

  zabbix-server:
    image: registry.dockermirror.com/zabbix/zabbix-server-mysql:ubuntu-7.0-latest
    container_name: zabbix-server
    environment:
      DB_SERVER_HOST: mysql
      MYSQL_DATABASE: zabbix
      MYSQL_USER: zabbix
      MYSQL_PASSWORD: huoxingxiaoliu
      MYSQL_ROOT_PASSWORD: huoxingxiaoliu
    depends_on:
      - mysql
    volumes:
      - /var/lib/zabbix:/var/lib/zabbix
    ports:
      - "10051:10051"
    networks:
      - zabbix-net

  zabbix-web:
    image: registry.dockermirror.com/zabbix/zabbix-web-apache-mysql:ubuntu-7.0-latest
    container_name: zabbix-web
    environment:
      DB_SERVER_HOST: mysql
      MYSQL_DATABASE: zabbix
      MYSQL_USER: zabbix
      MYSQL_PASSWORD: huoxingxiaoliu
      MYSQL_ROOT_PASSWORD: huoxingxiaoliu
      ZBX_SERVER_HOST: zabbix-server
      PHP_TZ: Asia/Shanghai
    depends_on:
      - zabbix-server
    ports:
      - "80:8080"
    networks:
      - zabbix-net

  zabbix-agent:
    image: registry.dockermirror.com/zabbix/zabbix-agent:ubuntu-7.0-latest
    container_name: zabbix-agent
    environment:
      ZBX_SERVER_HOST: zabbix-server
      HOSTNAME: zabbix-agent
    depends_on:
      - zabbix-server
    networks:
      - zabbix-net

volumes:
  mysql-data:
  zabbix-server-data:

networks:
  zabbix-net:
    driver: bridge
